services:
  - type: web
    name: intellibot-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn intellibot:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
